### ISSUE TITLE
App will not run without Debian packaging

### ISSUE THREAD

**Issue by m-roberts** [pi-top/pi-topOS-Web-Portal#132]
Currently the app requires the files to be in [these locations](https://github.com/pi-top/pt-web-portal/blob/master/debian/pt-web-portal.install):
```
pkg/pwdptwp.sh                              /usr/lib/pt-web-portal
src/expand-fs.sh                            /usr/lib/pt-web-portal
src/notify-on-port-busy.sh                  /usr/lib/pt-web-portal
src/server/Pipfile*                         /usr/lib/pt-web-portal
src/server/run.py                           /usr/lib/pt-web-portal
src/server/backend                          /usr/lib/pt-web-portal
```

The server should be able to be installed without Debian packaging, with full functionality. The `src/*.sh` scripts should be invoked by the backend with a relative path (or similar).

Ideally, the install file would look something like this:
```
pkg/pwdptwp.sh                        /usr/lib/pt-web-portal
src/server                            /usr/lib/pt-web-portal
```

Also, the app checks if onboarding is completed by looking for if `/etc/xdg/autostart/pt-os-setup.desktop` exists or not. This is only relevant because it is handled by the `postinst` Debian maintainer script. This means that the application is not going to work as intended if it is installed in any other way.

I am sure that there are other examples, so we should track these down and address them.

**Comment by jcapona** [comment]
So:
- `notify-on-port-busy.sh` is used by the `pt-web-portal-port-busy` systemd service, not the server.
- We definitely don't want to provide the `Pipfile` in the Debian package.

About FS expansion (#123), we could have our CLI handle the expansion, something similar to `raspi-config` ...

**Comment by m-roberts** [comment]
1) Technically `notify-on-port-busy.sh` is part of the Debian packaging, then. It shouldn't be in `src`, but `debian/extra` or something. Same for anything in `pkg`. Would need to look at how other packages do this.

2) Agreed on `Pipfile`s.

3) CLI could handle expansion, but the frontend would still be web portal. I am proposing that this actually be a different application (still with web renderer as frontend), specifically for initial setup. This would allow the web portal's scope to be very clear - it does not handle initial startup configuration. This isn't critical, but it would help maintainability.

**Comment by m-roberts** [comment]
I think I've figured out the optimal way to package this app.

```
A Python application that uses compiled frontend files as project data files

Use pybuild to build the entire application
    Modules:
        Backend server (`pt_os_web_portal`)
        Miniscreen (`pt_miniscreen_onboarding_assistant`)

    Python module build step: compile frontend
        How do we do this? setuptools-based

    top-level app setup.cfg:
        include project data files
        add CLI entrypoints

    services:
        use entrypoints (`/usr/bin/pt-os-wp-miniscreen-assistant`?)
```

Details TBD (how do you compile Typescript as part of a Python module build?), but this should get us most of the way there.

**Comment by m-roberts** [comment]
```

OPTION 1
--------

Python module has no knowledge of 'upstream' build files - it will take whatever it finds in the folder at install-time.

Debian packaging handles "pre-build" step, but pybuild still does actual app installation.



OPTION 2
--------

setup.py:
    import setuptools

    if __name__ == "__main__":

        # DO BUILD STEP

        # npm config set prefix ~/.local && \
        # npm install -g yarn && \
        # ~/.local/bin/yarn install && \
        # node_modules/react-scripts/bin/react-scripts.js build && \
        # mv build ../server/backend/

        setuptools.setup()
```
